{% set name = "google-cloud-container" %}
{% set version = "2.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7268325872b724b5d81093cb00de4ce1e756265bfbd6d7db86ed0a36ce47d64e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - google-api-core-grpc >=1.31.5,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0
    - grpc-google-iam-v1 >=0.12.4,<0.13dev
    - proto-plus >=1.15.0,<2.0.0dev
    - protobuf >=3.19.0,<4.0.0dev

test:
  imports:
    - google.cloud.container
    - google.cloud.container_v1
    - google.cloud.container_v1beta1
    - grpc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-container
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Google Container Engine API client library
  description: |
    **Python Client for Google Kubernetes Engine API**

    [Google Kubernetes Engine API](https://cloud.google.com/kubernetes-engine): The Google Kubernetes Engine API is used for
    building and managing container based applications, powered by the open source
    Kubernetes technology.

    - [Client Library Documentation](https://googleapis.dev/python/container/latest/index.html)
    - [Product Documentation](https://cloud.google.com/kubernetes-engine)

    **Quick Start**

    In order to use this library, you first need to go through the following steps:

    1. [Select or create a Cloud Platform project.](https://console.cloud.google.com/project)
    2. [Enable billing for your project.](https://cloud.google.com/billing/docs/how-to/modify-project#enable_billing_for_a_project)
    3. [Enable the Google Cloud Language API.](https://cloud.google.com/natural-language)
    4. [Setup Authentication.](https://googleapis.github.io/google-cloud-python/latest/core/auth.html)

    **Supported Python Versions**

    Python >= 3.5

    **Deprecated Python Versions**

    Python == 2.7
    - Python 2.7 support will be removed on January 1, 2020.
    - protobuf does not support Visual C++ 2008, windows py27 package not available

  doc_url: https://googleapis.dev/python/container/latest/index.html
  dev_url: https://github.com/googleapis/python-container

extra:
  recipe-maintainers:
    - xylar
    - BrentDorsey
    - parthea
