{% set name = "google-cloud-container" %}
{% set version = "2.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: eae6533e03de2509818dc3d4dba8c99b064a7812841c02eb371077bacc47f66b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip >=18.1
    - google-api-core-grpc >=1.22.2,<2.0.0dev
    - grpc-google-iam-v1 >=0.12.3,<0.13dev
    - proto-plus >=1.4.0
    - packaging >=14.3
  run:
    - python >=3.6
    - google-api-core-grpc
    - grpc-google-iam-v1
    - proto-plus
    - packaging

test:
  imports:
    - google.cloud.container
    - google.cloud.container_v1
    - google.cloud.container_v1beta1
    - grpc

about:
  home: https://github.com/googleapis/python-container
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Google Container Engine API client library
  description: |
    **Python Client for Google Kubernetes Engine API**

    [Google Kubernetes Engine API](https://cloud.google.com/kubernetes-engine): The Google Kubernetes Engine API is used for
    building and managing container based applications, powered by the open source
    Kubernetes technology.

    - [Client Library Documentation](https://googleapis.dev/python/container/latest/index.html)
    - [Product Documentation](https://cloud.google.com/kubernetes-engine)

    **Quick Start**

    In order to use this library, you first need to go through the following steps:

    1. [Select or create a Cloud Platform project.](https://console.cloud.google.com/project)
    2. [Enable billing for your project.](https://cloud.google.com/billing/docs/how-to/modify-project#enable_billing_for_a_project)
    3. [Enable the Google Cloud Language API.](https://cloud.google.com/natural-language)
    4. [Setup Authentication.](https://googleapis.github.io/google-cloud-python/latest/core/auth.html)

    **Supported Python Versions**

    Python >= 3.5

    **Deprecated Python Versions**

    Python == 2.7
    - Python 2.7 support will be removed on January 1, 2020.
    - protobuf does not support Visual C++ 2008, windows py27 package not available

  doc_url: https://googleapis.dev/python/container/latest/index.html
  dev_url: https://github.com/googleapis/python-container

extra:
  recipe-maintainers:
    - BrentDorsey
    - parthea
