travis:
  secure:
    BINSTAR_TOKEN: ALBQZAP7f7FA70F+JkMyxF4bslr/SErHudZ5Dbf2owgG9V8EgEpPuEaPoKwG/okiqwM3EeUmej6jeHc5z47b3f6FME59DLwTxyWwipRytt29tyfYOIi3fGc7Vf2AOnuh+kd7oiOyOqIvy3VSK8ZIUh4ER22zishIWly/Ub3MKNgioGgKMz9FOc0NFztSUiVJ81OxcIZSmSdOJDOi1J6Qot8iGHK6xix3keK20B4K3c9F0hHkT8VAADOv2j/dBhixIXum26dXCZZiLP8u+LnVPiS+hVWvLqeXFpkHPpyKkQBr8LEMOtaqsOsLzhv39zsq/0wM/WQWq10wwbfrM/30R+1AjFu8sQQZLLKLzFbjgrcRYQ/34Htk4e71HJOU/W9nT73t5QD6NJEIZUbbk88uNZesupcURIGKxkYR7+OwdrGIYDv8j8cRlhdYLNiEWv9XYFFhC1Ga8lOgYMU6fqvHMFpScM5oqw7d15W0EdRnoywjTYJBAX+W30n/yVMz/ekCqIHusBbEsUCwGD/zwmISciSVDI9HyqT1RpWlKFQwQGtMnnmgJmDEPUJmeiTRpAnKP2fd6rJ+1vKMro31rJTFEaOTgoWBETwT5u5RjpDSGueO/ma2SHd0EZ3uGgRO5057aTIwa6Z2Ilh/aMzgDPmA8FoMB7PukVxF5sDPyeJB34w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
